####  ch04.Numpy_Basic.ipynb 

In [26]:
from __future__ import division, absolute_import, print_function, nested_scopes, generators, with_statement, unicode_literals
# 하위 버전 파이썬에서도 상위 버전 기능을 사용할 수 있게 함 
from numpy.random import randn          # 표준정규분포에서 샘플링한 난수 반환
import numpy as np 
np.set_printoptions(precision=4, suppress=True) # 정밀도 : 소수점 조절, sup : 소수의 과학적 표현 억제 
%matplotlib inline 
# 명령의 출력을 셀 바로 아래에 (Rich Output(그림,도표,소리, 애니 등의 결과물))

In [27]:
data = randn(2,3)
data

array([[-0.6808,  0.5181,  0.3718],
       [ 0.2084,  0.0558, -0.6463]])

In [28]:
data.reshape((6,))

array([-0.6808,  0.5181,  0.3718,  0.2084,  0.0558, -0.6463])

- 반복문을 쓰지 않아도 한꺼번에 연산이 가능한 np.array

In [29]:
data + [[1,2,3]]    # broadcasting 

array([[0.3192, 2.5181, 3.3718],
       [1.2084, 2.0558, 2.3537]])

- 동일한 값을 갖는 list는 for문 x2 수행해야 함

In [30]:
l = data.tolist()   # list로 변환
l

[[-0.6808285676595532, 0.5181439435606874, 0.3717932340645751],
 [0.20841364564530657, 0.05578922368048204, -0.6463298056684461]]

In [31]:
for li in l:
    for i, k in zip(range(len(li)), [1,2,3]):
        li[i] +=k
l

[[0.31917143234044676, 2.5181439435606876, 3.371793234064575],
 [1.2084136456453065, 2.055789223680482, 2.3536701943315537]]

In [32]:
for li in l:        # 이 반복문에서의 li는 2차원 속 []인가? 
    for i,k in zip(range(len(li)), [1,2,3]):
        li[i] +=k       # 그래서 여기도? 
l

[[1.3191714323404469, 4.518143943560688, 6.371793234064575],
 [2.2084136456453063, 4.055789223680482, 5.353670194331554]]

In [33]:
data * 10, data+data, data*2

(array([[-6.8083,  5.1814,  3.7179],
        [ 2.0841,  0.5579, -6.4633]]),
 array([[-1.3617,  1.0363,  0.7436],
        [ 0.4168,  0.1116, -1.2927]]),
 array([[-1.3617,  1.0363,  0.7436],
        [ 0.4168,  0.1116, -1.2927]]))

In [34]:
print(data.shape, data.size, data.dtype)
# 형태, 요소 갯수, 타입 

(2, 3) 6 float64


- array 색인 

In [35]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr.shape, arr.dtype, arr.size

((2, 3), dtype('int32'), 6)

- 점색인

In [37]:
arr[1,2] # 1행/인덱스2

6

In [38]:
# 열 연속 색인
arr[1, 1:]

array([5, 6])

In [39]:
# 행 연속색인
arr[0:,2]

array([3, 6])

In [40]:
# 열행 연속색인 
arr[:], arr[:,:]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [41]:
arr[1,:], arr[1:,:], arr[1:] # 무슨 차이일까 

(array([4, 5, 6]), array([[4, 5, 6]]), array([[4, 5, 6]]))

In [42]:
arr[1:,:].shape

(1, 3)

- 행에 대한 점색인, 열에 대한 연속색인

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr[1], arr[1,:], arr[1].shape

(array([4, 5, 6]), array([4, 5, 6]), (3,))

- 열 팬시색인(불연속 색인)

In [45]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
# 정수 리스트 / 배열을 사용해 인덱싱 

In [47]:
arr2[[1,2]] # 1,2행 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
arr2[:,[0,3]]   # 모든 행 + 0, 3열 

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [49]:
arr2[0,[0,3]]

array([1, 4])

In [50]:
# 행과 열 각각 불연속 색인 = pairwise point indexing 
arr2[[0,1],[2,3]]
= np.array([arr[0,2], arr[1,3]])

SyntaxError: invalid syntax (<ipython-input-50-92bf5496f2b3>, line 3)

In [51]:
np.array([arr2[0,2], arr2[1,3]])


array([3, 8])

In [52]:
# 행과 열 각각 불연속 색인은 pairwise 식으로 점색인

[Quiz] arr에서 [[1, 3], [4, 6]]을 취하고 싶으면 어떻게 해야 할까?

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [55]:
# np.ix_() : 
gridIdx = np.ix_([0,1],[0,2])
gridIdx

(array([[0],
        [1]]),
 array([[0, 2]]))

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr[gridIdx]

array([[1, 3],
       [4, 6]])

In [58]:
# [[a[1,2] a[1,5]], [a[3,2] a[3,5]]] # 중간에 , 콤마(?)

[Quiz] 아래 ar에서 [[12,11,14], [2,1,4]]을 색인해보자.

In [59]:
ar = np.arange(20).reshape((4,5))
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
ar[np.ix_([2,0],[2,1,4])]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [61]:
br = ar[[2,0]]
br

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [62]:
br[:, [2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [63]:
# chaining index 
ar[[2,0]][:,[2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])

- 슬라이싱에서 step, turn 

In [64]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
li[5:3:-1]

[5, 4]

In [66]:
li[2:8]

[2, 3, 4, 5, 6, 7]

In [67]:
li[2:7:2], li[2:8:2]

([2, 4, 6], [2, 4, 6])

In [68]:
li[8:4:-3], li[8:2:-3]

([8, 5], [8, 5])

In [69]:
oneDarr = np.array(range(6))
oneDarr

array([0, 1, 2, 3, 4, 5])

In [70]:
oneDarr[2:5]

array([2, 3, 4])

In [71]:
oneDarr[5:2:-2]

array([5, 3])

In [72]:
oneDarr[-1:-5:-2]

array([5, 3])

- 불리언 색인

In [73]:
# 최 외곽차원, 행에 대한 색인만 가능 
arr.shape

(2, 3)

In [74]:
bArr = [True, False]
print(arr[bArr].shape)
arr[bArr]

(1, 3)


array([[1, 2, 3]])

In [75]:
bbArr = [True, True]
print(arr[bbArr].shape)
arr[bbArr]


(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
# point indexing
arr[0].shape

(3,)

In [77]:
# fancy indexing = a few point indexing : 열에 대한 불연속 색인 
arr[[0]]

array([[1, 2, 3]])

- [Quiz] arr에서 1, 5, 3의 값을 가져오는 색인을 해보자.

In [78]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
# 행, 열 불연속 cross 팬시 색인
arr[[0,1,0],[0,1,2]]

array([1, 5, 3])

- [Quiz] arr에서 [1,2,5,6] 가져오는 색인을 해보자.

In [80]:
arr[[0,0,1,1],[0,1,1,2]]

array([1, 2, 5, 6])

In [81]:
arr.reshape((-1,))[[True,True,False,False,True,True]]

array([1, 2, 5, 6])

In [ ]:
B = [True,True,False,False,True,True]
arr.reshape((-1,))[B]

array([1, 2, 5, 6])

- (***)[Quiz] arr에서 [[1,2], [5,6]] 가져오는 색인을 해보자

In [82]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
arr[[0,0,1,1],[0,1,1,2]].reshape(2,2)

array([[1, 2],
       [5, 6]])

In [130]:
arr.reshape((-1,))[[True,True,False,False,True,True,]].reshape(2,2)

array([[1, 2],
       [5, 6]])

In [133]:
print(arr[0, :2], arr[1,1:])
np.array([arr[0, :2], arr[1,1:]])

[1 2] [5 6]


array([[1, 2],
       [5, 6]])

bool indexing과 point, slicing, fancy 같이 사용하기

In [134]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
arr[0,[0,2]]

array([1, 3])

In [136]:
arr[0,[True,False,True]]

array([1, 3])

In [138]:
arr[0:1,[0,2]]  # slicing 색인은 같 차원 출력, 점색인은 n-1 차원 

array([[1, 3]])

In [139]:
arr[0:1,[True,False,True]]

array([[1, 3]])

In [140]:
arr[[False,True],[1,0]]

array([5, 4])

In [142]:
arr[[False,True],2]

array([6])

In [144]:
arr[[False,True],[True,False,True]]

array([4, 6])

arr의 속성 변경 
1) shape의 변경 - View

In [145]:
ar = np.array([[1,2,3,4],[5,6,7,8]])
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [148]:
ar2 = ar.reshape((4,2))
ar2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [149]:
ar2[0,0]=10
ar

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])

- [Quiz] ar3 = ar[0];   ar4 = ar[:,2];  ar5 = ar[[0,1], 1] 일때 :

- ar3[1] = 0;   ar4[1] = 0;     ar5[1] = 0 어떤 결과가 나올까?
- 왜 그런 결과가 나올까? 설명해보세요.

In [160]:
ar3 = ar[0]
ar3

array([2, 2, 2, 2])

In [158]:
ar4 = ar[:,2]
ar4

array([2, 2])

In [159]:
ar5 = ar[[0,1],1]
ar5

array([2, 6])