####  ch04.Numpy_Basic.ipynb 

In [26]:
from __future__ import division, absolute_import, print_function, nested_scopes, generators, with_statement, unicode_literals
# 하위 버전 파이썬에서도 상위 버전 기능을 사용할 수 있게 함 
from numpy.random import randn          # 표준정규분포에서 샘플링한 난수 반환
import numpy as np 
np.set_printoptions(precision=4, suppress=True) # 정밀도 : 소수점 조절, sup : 소수의 과학적 표현 억제 
%matplotlib inline 
# 명령의 출력을 셀 바로 아래에 (Rich Output(그림,도표,소리, 애니 등의 결과물))

In [27]:
data = randn(2,3)
data

array([[-0.2335, -0.1348, -0.1887],
       [-0.412 , -1.0702, -0.4097]])

In [28]:
data.reshape((6,))

array([-0.2335, -0.1348, -0.1887, -0.412 , -1.0702, -0.4097])

- 반복문을 쓰지 않아도 한꺼번에 연산이 가능한 np.array

In [29]:
data + [[1,2,3]]    # broadcasting 

array([[0.7665, 1.8652, 2.8113],
       [0.588 , 0.9298, 2.5903]])

- 동일한 값을 갖는 list는 for문 x2 수행해야 함

In [30]:
l = data.tolist()   # list로 변환
l

[[-0.2334795298405907, -0.1348437274737777, -0.18873976686376565],
 [-0.4119905504509189, -1.0701698485670446, -0.40967967285584084]]

In [31]:
for li in l:
    for i, k in zip(range(len(li)), [1,2,3]):
        li[i] +=k
l

[[0.7665204701594093, 1.8651562725262223, 2.811260233136234],
 [0.5880094495490811, 0.9298301514329554, 2.590320327144159]]

In [32]:
for li in l:        # 이 반복문에서의 li는 2차원 속 []인가? 
    for i,k in zip(range(len(li)), [1,2,3]):
        li[i] +=k       # 그래서 여기도? 
l

[[1.7665204701594093, 3.8651562725262223, 5.811260233136235],
 [1.588009449549081, 2.9298301514329554, 5.590320327144159]]

In [33]:
data * 10, data+data, data*2

(array([[ -2.3348,  -1.3484,  -1.8874],
        [ -4.1199, -10.7017,  -4.0968]]),
 array([[-0.467 , -0.2697, -0.3775],
        [-0.824 , -2.1403, -0.8194]]),
 array([[-0.467 , -0.2697, -0.3775],
        [-0.824 , -2.1403, -0.8194]]))

In [34]:
print(data.shape, data.size, data.dtype)
# 형태, 요소 갯수, 타입 

(2, 3) 6 float64


- array 색인 

In [35]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr.shape, arr.dtype, arr.size

((2, 3), dtype('int32'), 6)

- 점색인

In [37]:
arr[1,2] # 1행/인덱스2

6

In [38]:
# 열 연속 색인
arr[1, 1:]

array([5, 6])

In [39]:
# 행 연속색인
arr[0:,2]

array([3, 6])

In [40]:
# 열행 연속색인 
arr[:], arr[:,:]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [41]:
arr[1,:], arr[1:,:], arr[1:] # 무슨 차이일까 

(array([4, 5, 6]), array([[4, 5, 6]]), array([[4, 5, 6]]))

In [42]:
arr[1:,:].shape

(1, 3)

- 행에 대한 점색인, 열에 대한 연속색인

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr[1], arr[1,:], arr[1].shape

(array([4, 5, 6]), array([4, 5, 6]), (3,))

- 열 팬시색인(불연속 색인)

In [45]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
# 정수 리스트 / 배열을 사용해 인덱싱 

In [47]:
arr2[[1,2]] # 1,2행 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
arr2[:,[0,3]]   # 모든 행 + 0, 3열 

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [49]:
arr2[0,[0,3]]

array([1, 4])

In [50]:
# 행과 열 각각 불연속 색인 = pairwise point indexing 
arr2[[0,1],[2,3]]
= np.array([arr[0,2], arr[1,3]])

SyntaxError: invalid syntax (<ipython-input-50-92bf5496f2b3>, line 3)

In [51]:
np.array([arr2[0,2], arr2[1,3]])


array([3, 8])

In [ ]:
# 행과 열 각각 불연속 색인은 pairwise 식으로 점색인

[Quiz] arr에서 [[1, 3], [4, 6]]을 취하고 싶으면 어떻게 해야 할까?

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [ ]:
# np.ix_() : 
gridIdx = np.ix_([0,1],[0,2])
gridIdx

(array([[0],
        [1]]),
 array([[0, 2]]))

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[gridIdx]

array([[1, 3],
       [4, 6]])

In [ ]:
[[a[1,2] a[1,5]], [a[3,2] a[3,5]]] # 중간에 , 콤마(?)

IndexError: index 5 is out of bounds for axis 1 with size 4

[Quiz] 아래 ar에서 [[12,11,14], [2,1,4]]을 색인해보자.

In [54]:
ar = np.arange(20).reshape((4,5))
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
ar[np.ix_([2,0],[2,1,4])]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [55]:
br = ar[[2,0]]
br

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [57]:
br[:, [2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])