####  ch04.Numpy_Basic.ipynb 

In [1]:
from __future__ import division, absolute_import, print_function, nested_scopes, generators, with_statement, unicode_literals
# 하위 버전 파이썬에서도 상위 버전 기능을 사용할 수 있게 함 
from numpy.random import randn          # 표준정규분포에서 샘플링한 난수 반환
import numpy as np 
np.set_printoptions(precision=4, suppress=True) # 정밀도 : 소수점 조절, sup : 소수의 과학적 표현 억제 
%matplotlib inline 
# 명령의 출력을 셀 바로 아래에 (Rich Output(그림,도표,소리, 애니 등의 결과물))

In [2]:
data = randn(2,3)
data

array([[ 0.3399, -0.1774, -0.1196],
       [-2.1205,  1.8593,  1.3979]])

In [3]:
data.reshape((6,))

array([ 0.3399, -0.1774, -0.1196, -2.1205,  1.8593,  1.3979])

- 반복문을 쓰지 않아도 한꺼번에 연산이 가능한 np.array

In [4]:
data + [[1,2,3]]    # broadcasting 

array([[ 1.3399,  1.8226,  2.8804],
       [-1.1205,  3.8593,  4.3979]])

- 동일한 값을 갖는 list는 for문 x2 수행해야 함

In [5]:
l = data.tolist()   # list로 변환
l

[[0.3399069158970756, -0.1773763956968377, -0.1195703823568538],
 [-2.1204830840314095, 1.8592633673372179, 1.397885428574536]]

In [6]:
for li in l:
    for i, k in zip(range(len(li)), [1,2,3]):
        li[i] +=k
l

[[1.3399069158970756, 1.8226236043031623, 2.8804296176431463],
 [-1.1204830840314095, 3.859263367337218, 4.397885428574536]]

In [7]:
for li in l:        # 이 반복문에서의 li는 2차원 속 []인가? 
    for i,k in zip(range(len(li)), [1,2,3]):
        li[i] +=k       # 그래서 여기도? 
l

[[2.3399069158970756, 3.8226236043031623, 5.880429617643147],
 [-0.1204830840314095, 5.859263367337218, 7.397885428574536]]

In [8]:
data * 10, data+data, data*2

(array([[  3.3991,  -1.7738,  -1.1957],
        [-21.2048,  18.5926,  13.9789]]),
 array([[ 0.6798, -0.3548, -0.2391],
        [-4.241 ,  3.7185,  2.7958]]),
 array([[ 0.6798, -0.3548, -0.2391],
        [-4.241 ,  3.7185,  2.7958]]))

In [9]:
print(data.shape, data.size, data.dtype)
# 형태, 요소 갯수, 타입 

(2, 3) 6 float64


- array 색인 

In [10]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.shape, arr.dtype, arr.size

((2, 3), dtype('int32'), 6)

- 점색인

In [12]:
arr[1,2] # 1행/인덱스2

6

In [13]:
# 열 연속 색인
arr[1, 1:]

array([5, 6])

In [14]:
# 행 연속색인
arr[0:,2]

array([3, 6])

In [15]:
# 열행 연속색인 
arr[:], arr[:,:]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [16]:
arr[1,:], arr[1:,:], arr[1:] # 무슨 차이일까 

(array([4, 5, 6]), array([[4, 5, 6]]), array([[4, 5, 6]]))

In [17]:
arr[1:,:].shape

(1, 3)

- 행에 대한 점색인, 열에 대한 연속색인

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr[1], arr[1,:], arr[1].shape

(array([4, 5, 6]), array([4, 5, 6]), (3,))

- 열 팬시색인(불연속 색인)

In [20]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
# 정수 리스트 / 배열을 사용해 인덱싱 

In [22]:
arr2[[1,2]] # 1,2행 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr2[:,[0,3]]   # 모든 행 + 0, 3열 

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [24]:
arr2[0,[0,3]]

array([1, 4])

In [25]:
# 행과 열 각각 불연속 색인 = pairwise point indexing 
arr2[[0,1],[2,3]]
= np.array([arr[0,2], arr[1,3]])

SyntaxError: invalid syntax (<ipython-input-25-92bf5496f2b3>, line 3)

In [26]:
np.array([arr2[0,2], arr2[1,3]])


array([3, 8])

In [27]:
# 행과 열 각각 불연속 색인은 pairwise 식으로 점색인

[Quiz] arr에서 [[1, 3], [4, 6]]을 취하고 싶으면 어떻게 해야 할까?

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [30]:
# np.ix_() : 
gridIdx = np.ix_([0,1],[0,2])
gridIdx

(array([[0],
        [1]]),
 array([[0, 2]]))

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr[gridIdx]

array([[1, 3],
       [4, 6]])

In [33]:
# [[a[1,2] a[1,5]], [a[3,2] a[3,5]]] # 중간에 , 콤마(?)

[Quiz] 아래 ar에서 [[12,11,14], [2,1,4]]을 색인해보자.

In [34]:
ar = np.arange(20).reshape((4,5))
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
ar[np.ix_([2,0],[2,1,4])]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [36]:
br = ar[[2,0]]
br

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [37]:
br[:, [2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [38]:
# chaining index 
ar[[2,0]][:,[2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])

- 슬라이싱에서 step, turn 

In [39]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
li[5:3:-1]

[5, 4]

In [41]:
li[2:8]

[2, 3, 4, 5, 6, 7]

In [42]:
li[2:7:2], li[2:8:2]

([2, 4, 6], [2, 4, 6])

In [43]:
li[8:4:-3], li[8:2:-3]

([8, 5], [8, 5])

In [44]:
oneDarr = np.array(range(6))
oneDarr

array([0, 1, 2, 3, 4, 5])

In [45]:
oneDarr[2:5]

array([2, 3, 4])

In [46]:
oneDarr[5:2:-2]

array([5, 3])

In [47]:
oneDarr[-1:-5:-2]

array([5, 3])

- 불리언 색인

In [48]:
# 최 외곽차원, 행에 대한 색인만 가능 
arr.shape

(2, 3)

In [49]:
bArr = [True, False]
print(arr[bArr].shape)
arr[bArr]

(1, 3)


array([[1, 2, 3]])

In [50]:
bbArr = [True, True]
print(arr[bbArr].shape)
arr[bbArr]


(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# point indexing
arr[0].shape

(3,)

In [52]:
# fancy indexing = a few point indexing : 열에 대한 불연속 색인 
arr[[0]]

array([[1, 2, 3]])

- [Quiz] arr에서 1, 5, 3의 값을 가져오는 색인을 해보자.

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# 행, 열 불연속 cross 팬시 색인
arr[[0,1,0],[0,1,2]]

array([1, 5, 3])

- [Quiz] arr에서 [1,2,5,6] 가져오는 색인을 해보자.

In [55]:
arr[[0,0,1,1],[0,1,1,2]]

array([1, 2, 5, 6])

In [56]:
arr.reshape((-1,))[[True,True,False,False,True,True]]

array([1, 2, 5, 6])

In [57]:
B = [True,True,False,False,True,True]
arr.reshape((-1,))[B]

array([1, 2, 5, 6])

- (***)[Quiz] arr에서 [[1,2], [5,6]] 가져오는 색인을 해보자

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr[[0,0,1,1],[0,1,1,2]].reshape(2,2)

array([[1, 2],
       [5, 6]])

In [60]:
arr.reshape((-1,))[[True,True,False,False,True,True,]].reshape(2,2)

array([[1, 2],
       [5, 6]])

In [61]:
print(arr[0, :2], arr[1,1:])
np.array([arr[0, :2], arr[1,1:]])

[1 2] [5 6]


array([[1, 2],
       [5, 6]])

bool indexing과 point, slicing, fancy 같이 사용하기

In [62]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr[0,[0,2]]

array([1, 3])

In [64]:
arr[0,[True,False,True]]

array([1, 3])

In [65]:
arr[0:1,[0,2]]  # slicing 색인은 같 차원 출력, 점색인은 n-1 차원 

array([[1, 3]])

In [66]:
arr[0:1,[True,False,True]]

array([[1, 3]])

In [67]:
arr[[False,True],[1,0]]

array([5, 4])

In [68]:
arr[[False,True],2]

array([6])

In [69]:
arr[[False,True],[True,False,True]]

array([4, 6])

arr의 속성 변경 
1) shape의 변경 - View

In [70]:
ar = np.array([[1,2,3,4],[5,6,7,8]])
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
ar2 = ar.reshape((4,2))
ar2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
ar2[0,0]=10
ar

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])

- [Quiz] ar3 = ar[0];   ar4 = ar[:,2];  ar5 = ar[[0,1], 1] 일때 :

- ar3[1] = 0;   ar4[1] = 0;     ar5[1] = 0 어떤 결과가 나올까?
- 왜 그런 결과가 나올까? 설명해보세요.

In [76]:
ar

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [77]:
ar3 = ar[0]
print(ar3)
ar3[1]=0
ar3


[10  2  3  4]


array([10,  0,  3,  4])

In [78]:
ar4 = ar[:,2]
print(ar4)
ar4[1]=0
ar4

[3 7]


array([3, 0])

In [80]:
ar5 = ar[[0,1],1]
print(ar5)
ar5[1]=0
ar5

[0 6]


array([0, 0])

In [81]:
ar

array([[10,  0,  3,  4],
       [ 5,  6,  0,  8]])

In [82]:
# ar3, ar4는 ar의 View이고, ar5는 ar과 아무 관련이 없다.
# 행에 대한 점색인, 연속색인은 View를, fancy색인은 copy를 발생S
# 어떤 것이 View이고 copy인지 모르겠다면, copy해서 사용해야 합니다. 
# 가급적 View를 사용하는 것이 좋다. 

In [86]:
ar6 = ar[0].copy()
ar6[1]=100
ar, ar6

(array([[10,  0,  3,  4],
        [ 5,  6,  0,  8]]),
 array([ 10, 100,   3,   4]))

dtype의 변경 - now object

In [94]:
# ndarray의 ar의 dtype 변경시, 새로운 ndarray 객체 ar3가 생성되며, 
# 이 객체는 ar과 무관하다. 

In [91]:
ar3 = ar.astype('float')
ar3

array([[10.,  0.,  3.,  4.],
       [ 5.,  6.,  0.,  8.]])

In [92]:
ar

array([[10,  0,  3,  4],
       [ 5,  6,  0,  8]])

In [97]:
ar3[0,0]=30
ar, ar3

(array([[10,  0,  3,  4],
        [ 5,  6,  0,  8]]),
 array([[30.,  0.,  3.,  4.],
        [ 5.,  6.,  0.,  8.]]))

In [98]:
# int형 array에 float를 대입하면, 소수부는 버린다. 
ar.dtype

dtype('int32')

In [100]:
ar[0,0]=1.9
ar

array([[1, 0, 3, 4],
       [5, 6, 0, 8]])