####  ch04.Numpy_Basic.ipynb 

In [1]:
from __future__ import division, absolute_import, print_function, nested_scopes, generators, with_statement, unicode_literals
# 하위 버전 파이썬에서도 상위 버전 기능을 사용할 수 있게 함 
from numpy.random import randn          # 표준정규분포에서 샘플링한 난수 반환
import numpy as np 
np.set_printoptions(precision=4, suppress=True) # 정밀도 : 소수점 조절, sup : 소수의 과학적 표현 억제 
%matplotlib inline 
# 명령의 출력을 셀 바로 아래에 (Rich Output(그림,도표,소리, 애니 등의 결과물))

In [2]:
data = randn(2,3)
data

array([[-0.4201,  1.4222,  2.0086],
       [-0.1424, -1.7817,  0.5176]])

In [3]:
data.reshape((6,))

array([-0.4201,  1.4222,  2.0086, -0.1424, -1.7817,  0.5176])

- 반복문을 쓰지 않아도 한꺼번에 연산이 가능한 np.array

In [4]:
data + [[1,2,3]]    # broadcasting 

array([[0.5799, 3.4222, 5.0086],
       [0.8576, 0.2183, 3.5176]])

- 동일한 값을 갖는 list는 for문 x2 수행해야 함

In [5]:
l = data.tolist()   # list로 변환
l

[[-0.42012079214507486, 1.4221627932248155, 2.008618632323058],
 [-0.14244714303993078, -1.7816742801034464, 0.517626786349396]]

In [6]:
for li in l:
    for i, k in zip(range(len(li)), [1,2,3]):
        li[i] +=k
l

[[0.5798792078549251, 3.4221627932248158, 5.008618632323058],
 [0.8575528569600692, 0.21832571989655358, 3.517626786349396]]

In [7]:
for li in l:        # 이 반복문에서의 li는 2차원 속 []인가? 
    for i,k in zip(range(len(li)), [1,2,3]):
        li[i] +=k       # 그래서 여기도? 
l

[[1.579879207854925, 5.422162793224816, 8.008618632323058],
 [1.8575528569600692, 2.2183257198965536, 6.517626786349396]]

In [8]:
data * 10, data+data, data*2

(array([[ -4.2012,  14.2216,  20.0862],
        [ -1.4245, -17.8167,   5.1763]]),
 array([[-0.8402,  2.8443,  4.0172],
        [-0.2849, -3.5633,  1.0353]]),
 array([[-0.8402,  2.8443,  4.0172],
        [-0.2849, -3.5633,  1.0353]]))

In [9]:
print(data.shape, data.size, data.dtype)
# 형태, 요소 갯수, 타입 

(2, 3) 6 float64


- array 색인 

In [10]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.shape, arr.dtype, arr.size

((2, 3), dtype('int32'), 6)

- 점색인

In [12]:
arr[1,2] # 1행/인덱스2

6

In [13]:
# 열 연속 색인
arr[1, 1:]

array([5, 6])

In [14]:
# 행 연속색인
arr[0:,2]

array([3, 6])

In [15]:
# 열행 연속색인 
arr[:], arr[:,:]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [16]:
arr[1,:], arr[1:,:], arr[1:] # 무슨 차이일까 

(array([4, 5, 6]), array([[4, 5, 6]]), array([[4, 5, 6]]))

In [17]:
arr[1:,:].shape

(1, 3)

- 행에 대한 점색인, 열에 대한 연속색인

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr[1], arr[1,:], arr[1].shape

(array([4, 5, 6]), array([4, 5, 6]), (3,))

- 열 팬시색인(불연속 색인)

In [20]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
# 정수 리스트 / 배열을 사용해 인덱싱 

In [22]:
arr2[[1,2]] # 1,2행 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr2[:,[0,3]]   # 모든 행 + 0, 3열 

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [24]:
arr2[0,[0,3]]

array([1, 4])

In [25]:
# 행과 열 각각 불연속 색인 = pairwise point indexing 
arr2[[0,1],[2,3]]
= np.array([arr[0,2], arr[1,3]])

SyntaxError: invalid syntax (<ipython-input-25-92bf5496f2b3>, line 3)

In [26]:
np.array([arr2[0,2], arr2[1,3]])


array([3, 8])

In [27]:
# 행과 열 각각 불연속 색인은 pairwise 식으로 점색인

[Quiz] arr에서 [[1, 3], [4, 6]]을 취하고 싶으면 어떻게 해야 할까?

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [ ]:
# np.ix_() : 
gridIdx = np.ix_([0,1],[0,2])
gridIdx

(array([[0],
        [1]]),
 array([[0, 2]]))

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[gridIdx]

array([[1, 3],
       [4, 6]])

In [ ]:
[[a[1,2] a[1,5]], [a[3,2] a[3,5]]] # 중간에 , 콤마(?)

IndexError: index 5 is out of bounds for axis 1 with size 4

[Quiz] 아래 ar에서 [[12,11,14], [2,1,4]]을 색인해보자.

In [35]:
ar = np.arange(20).reshape((4,5))
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
ar[np.ix_([2,0],[2,1,4])]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [39]:
br = ar[[2,0]]
br

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [40]:
br[:, [2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])

In [41]:
# chaining index 
ar[[2,0]][:,[2,1,4]]

array([[12, 11, 14],
       [ 2,  1,  4]])

- 슬라이싱에서 step, turn 

In [43]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
li[5:3:-1]

([5, 4], [2, 3, 4, 5, 6, 7])

In [50]:
li[2:8]

[2, 3, 4, 5, 6, 7]

In [52]:
li[2:7:2], li[2:8:2]

([2, 4, 6], [2, 4, 6])

In [54]:
li[8:4:-3], li[8:2:-3]

([8, 5], [8, 5])

In [56]:
oneDarr = np.array(range(6))
oneDarr

array([0, 1, 2, 3, 4, 5])

In [57]:
oneDarr[2:5]

array([2, 3, 4])

In [60]:
oneDarr[5:2:-2]

array([5, 3])

In [62]:
oneDarr[-1:-5:-2]

array([5, 3])

- 불리언 색인

In [68]:
# 최 외곽차원, 행에 대한 색인만 가능 
arr.shape

(2, 3)

In [74]:
bArr = [True, False]
print(arr[bArr].shape)
arr[bArr]

(1, 3)


array([[1, 2, 3]])

In [73]:
bbArr = [True, True]
print(arr[bbArr].shape)
arr[bbArr]


(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# point indexing
arr[0].shape

(3,)

In [76]:
# fancy indexing = a few point indexing : 열에 대한 불연속 색인 
arr[[0]]

array([[1, 2, 3]])

- [Quiz] arr에서 1, 5, 3의 값을 가져오는 색인을 해보자.

In [77]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
# 행, 열 불연속 cross 팬시 색인
arr[[0,1,0],[0,1,2]]

array([1, 5, 3])

- [Quiz] arr에서 [1,2,5,6] 가져오는 색인을 해보자.

In [81]:
arr[[0,0,1,1],[0,1,1,2]]

array([1, 2, 5, 6])

In [85]:
arr.reshape((-1,))[[True,True,False,False,True,True]]

array([1, 2, 5, 6])

In [86]:
B = [True,True,False,False,True,True]
arr.reshape((-1,))[B]

array([1, 2, 5, 6])