####  ch04.Numpy_Basic.ipynb 

In [4]:
from __future__ import division, absolute_import, print_function, nested_scopes, generators, with_statement, unicode_literals
# 하위 버전 파이썬에서도 상위 버전 기능을 사용할 수 있게 함 
from numpy.random import randn          # 표준정규분포에서 샘플링한 난수 반환
import numpy as np 
np.set_printoptions(precision=4, suppress=True) # 정밀도 : 소수점 조절, sup : 소수의 과학적 표현 억제 
%matplotlib inline 
# 명령의 출력을 셀 바로 아래에 (Rich Output(그림,도표,소리, 애니 등의 결과물))

In [6]:
data = randn(2,3)
data

array([[ 0.6686,  0.0662,  0.024 ],
       [ 1.0567, -0.3529, -0.4702]])

In [8]:
data.reshape((6,))

array([ 0.6686,  0.0662,  0.024 ,  1.0567, -0.3529, -0.4702])

- 반복문을 쓰지 않아도 한꺼번에 연산이 가능한 np.array

In [16]:
data + [[1,2,3]]    # broadcasting 

array([[1.6686, 2.0662, 3.024 ],
       [2.0567, 1.6471, 2.5298]])

- 동일한 값을 갖는 list는 for문 x2 수행해야 함

In [17]:
l = data.tolist()   # list로 변환
l

[[0.668555736683668, 0.06620119728387372, 0.024019755649714456],
 [1.056658791707645, -0.3529124105524884, -0.470209252934224]]

In [18]:
for li in l:
    for i, k in zip(range(len(li)), [1,2,3]):
        li[i] +=k
l

[[1.6685557366836679, 2.0662011972838736, 3.0240197556497144],
 [2.056658791707645, 1.6470875894475117, 2.529790747065776]]

In [21]:
for li in l:        # 이 반복문에서의 li는 2차원 속 []인가? 
    for i,k in zip(range(len(li)), [1,2,3]):
        li[i] +=k       # 그래서 여기도? 
l

[[3.668555736683668, 6.066201197283874, 9.024019755649714],
 [4.056658791707645, 5.647087589447512, 8.529790747065777]]

In [24]:
data * 10, data+data, data*2

(array([[ 6.6856,  0.662 ,  0.2402],
        [10.5666, -3.5291, -4.7021]]),
 array([[ 1.3371,  0.1324,  0.048 ],
        [ 2.1133, -0.7058, -0.9404]]),
 array([[ 1.3371,  0.1324,  0.048 ],
        [ 2.1133, -0.7058, -0.9404]]))

In [26]:
print(data.shape, data.size, data.dtype)
# 형태, 요소 갯수, 타입 

(2, 3) 6 float64


- array 색인 

In [27]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr.shape, arr.dtype, arr.size

((2, 3), dtype('int32'), 6)

- 점색인

In [31]:
arr[1,2] # 1행/인덱스2

6

In [51]:
# 열 연속 색인
arr[1, 1:]

array([5, 6])

In [53]:
# 행 연속색인
arr[0:,2]

array([3, 6])

In [54]:
# 열행 연속색인 
arr[:], arr[:,:]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [45]:
arr[1,:], arr[1:,:], arr[1:] # 무슨 차이일까 

(array([4, 5, 6]), array([[4, 5, 6]]), array([[4, 5, 6]]))

In [46]:
arr[1:,:].shape

(1, 3)

- 행에 대한 점색인, 열에 대한 연속색인

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr[1], arr[1,:], arr[1].shape

(array([4, 5, 6]), array([4, 5, 6]), (3,))

- 열 팬시색인(불연속 색인)

In [59]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
# 정수 리스트 / 배열을 사용해 인덱싱 

In [60]:
arr2[[1,2]] # 1,2행 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
arr2[:,[0,3]]   # 모든 행 + 0, 3열 

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [63]:
arr2[0,[0,3]]

array([1, 4])

In [64]:
# 행과 열 각각 불연속 색인 = pairwise point indexing 
arr2[[0,1],[2,3]]
= np.array([arr[0,2], arr[1,3]])

array([3, 8])

In [66]:
np.array([arr2[0,2], arr2[1,3]])


array([3, 8])

In [67]:
# 행과 열 각각 불연속 색인은 pairwise 식으로 점색인

[Quiz] arr에서 [[1, 3], [4, 6]]을 취하고 싶으면 어떻게 해야 할까?

In [70]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [72]:
# np.ix_() : 
gridIdx = np.ix_([0,1],[0,2])
gridIdx

(array([[0],
        [1]]),
 array([[0, 2]]))

In [74]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr[gridIdx]

array([[1, 3],
       [4, 6]])

In [80]:
[[a[1,2] a[1,5]], [a[3,2] a[3,5]]] # 중간에 , 콤마(?)

IndexError: index 5 is out of bounds for axis 1 with size 4

[Quiz] 아래 ar에서 [[12,11,14], [2,1,4]]을 색인해보자.

In [82]:
ar = np.arange(20).reshape((4,5))
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
ar[np.ix_([2,0],[2,1,4])]

array([[12, 11, 14],
       [ 2,  1,  4]])