In [1]:
import numpy as np

# 1

In [4]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
a = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [2]:
# T (연습문제는 한 줄로 끝내도록)
np.arange(10,90,10).reshape(2,4)


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
# T2
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 2

In [12]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
m = np.arange(15).reshape(3,5)

- 이 행렬에서 값 7을 인덱싱한다

In [7]:
m[1,2]

7

In [8]:
m[1][2]

7

- 이 행렬에서 값 14 을 인덱싱한다.

In [9]:
m[2,4], m[2][4]

(14, 14)

In [7]:
# T
m[-1,-1]

14

- 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [10]:
m[1,1:3]
#한 쪽만 슬라이스면 1차원 출력[인덱스,슬라이스]

array([6, 7])

In [8]:
m[1:2,1:3]
# 두 쪽 다 슬라이스면 2차원 출력 [슬라이스, 슬라이스]

array([[6, 7]])

- 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [11]:
m[1:,2:3] # 틀렸어! 2차원 

array([[ 7],
       [12]])

In [9]:
# T 
m[1:,2]         # 1차원 

array([ 7, 12])

- 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [12]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [10]:
# T 
m[:-1,3:]

array([[3, 4],
       [8, 9]])

# 3

- 불리안 인덱스

In [14]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
f=m.reshape(-1)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- 이 배열에서 3의 배수를 찾아라.

In [15]:
# T 
f[f%3==0]

# 원소의 값이 T일 때 튕겨져 나오고 아니면 사라지고 (필터링)

array([ 0,  3,  6,  9, 12])

In [14]:
f%3 ==0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False])

In [15]:
print(np.where(f%3==0))

# 0은 0제외 모든 정수의 배수니까 제외 안 해도 괜찮을까? 
# where을 배운 기억은 없다 

(array([ 0,  3,  6,  9, 12], dtype=int64),)


- 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [16]:
# T
f[f%4==1]

array([ 1,  5,  9, 13])

In [16]:
print(np.where(f%4==1))

(array([ 1,  5,  9, 13], dtype=int64),)


- 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [17]:
# T 
f[np.logical_and(f%3==0,f%4==1)]
# 대괄호 내 and X / logicla_and/or 사용 

array([9])

In [17]:
print(np.where(f%3==0 and f%4==1))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 4

In [ ]:
a=np.eye(5,5,k=-1,dtype=np.int8)
b=np.eye(5,5,k=0,dtype=np.int8)
c=np.eye(5,5,k=1,dtype=np.int8)
3*a + 2*b + c 

# 대박! 풀었다 
# dtype의 경우 int 정도로 해도 괜찮음 

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]], dtype=int8)

In [19]:
# T 
np.eye(5,5,-1,int)*3 + np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

# 5

In [23]:
# T
np.random.seed(2021)
a = np.random.uniform(0,10,30).reshape(5,6).round(4)        # round 4 - 소수점 4자리까지 맞추는 함수같음..
a

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [24]:
# T 전체의 최댓값
a.max()

9.9724

In [25]:
# T 행의 합 1
a.sum(axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [27]:
# T 행의 합 2
np.sum(a,axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [28]:
# T 행의 최댓값
a.max(axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [ ]:
# T 각 열의 평균
a.mean(axis=0)
a.mean(axis=0)

In [29]:
# T 각 열의 최솟값
a.min(axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

In [ ]:
a = np.random.uniform(0,10,(5,6))           # 실수 추출 : uniform
a

array([[0.5903031 , 2.22007595, 4.97792321, 9.1094745 , 3.16669711,
        5.51994293],
       [0.27573375, 3.6380522 , 0.17695254, 6.80429652, 0.24486672,
        6.00128773],
       [3.99194862, 7.27533636, 5.10287833, 5.50345055, 3.68114563,
        7.76868373],
       [8.77509469, 0.45274346, 9.18777908, 1.50218159, 4.16146269,
        7.17272145],
       [5.31113856, 7.50492907, 0.69780529, 2.15038686, 4.45191943,
        5.15116823]])

In [ ]:
# 전체의 최댓값 
a.max()

9.187779081972552

In [ ]:
# 각 행의 합 
a.sum(axis=1)

array([25.5844168 , 17.14118946, 33.32344323, 31.25198297, 25.26734745])

In [ ]:
# 각 행의 최댓값 
a.max(axis=1)

array([9.1094745 , 6.80429652, 7.76868373, 9.18777908, 7.50492907])

In [ ]:
# 각 열의 평균
a.mean(axis=0)

array([3.78884375, 4.21822741, 4.02866769, 5.013958  , 3.14121832,
       6.32276081])

In [ ]:
# 각 열의 최솟값
a.min(axis=0)

array([0.27573375, 0.45274346, 0.17695254, 1.50218159, 0.24486672,
       5.15116823])

# 6

- 영어 성적을 기준으로 = 보편적으로 성적은 내림차순(100 99 71 46) + 영어 성적의 인덱스를 따라라(indice)

In [30]:
# T : sorting 
score = np.array([[ 1, 2, 3, 4],[ 46, 99, 100, 71],[ 81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [33]:
# T 
# 영어 성적을 argsort()

indices = np.argsort(score[1])      # score의 1행의 인덱스 순서를 찾으세요
indices

array([0, 3, 1, 2], dtype=int64)

In [34]:
# T 
# 내림차순으로 다시 
indices[::-1] 

array([2, 1, 3, 0], dtype=int64)

In [37]:
# T 
score[:,indices[::-1]]      # score 모든 행에 걸쳐서 / 열 정렬은 indices[::1]로 

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [35]:
# T
# 한줄로 만들면 
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [18]:
a = np.array([[ 1, 2, 3, 4],[ 46, 99, 100, 71],[ 81, 59, 90, 100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [22]:
# 2 번째 행을 기준으로 각 열을 재정렬하라 
# 전체 오름차순 재정렬-영어 정렬 인덱스 순서 기억한다음 - 다른 데이터들의 인덱스 순서 맞추는 방법으로 풀어보자
a.argsort()


array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]], dtype=int64)

In [19]:
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
a[[0,3,1,2],[0,3,1,2],[0,3,1,2]]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

# 7

In [38]:
# T
np.random.seed(2021)    # 선생님하고 동기화하는 것에 불과
dice = np.random.randint(1,7,100)       # 랜덤 모듈에서 정수의 randint(1,6)
dice                                        # 어디서 1,7이라고? 

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [40]:
# T
np.mean(dice)

3.7

In [41]:
# T : dice array에서 고유값 
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [42]:
# dice array에서 고유값 및 그것의 갯수 (1은 몇 번 나왔는가 등)
np.unique(dice,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [44]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

# unique, counts를 딕셔너리로 보기 

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [ ]:
import random 
for i in range(100):
    dice = np.random.randint(1,6)

dice


3

In [ ]:
dice = np.random.randint(1,7,size=100)
dice

array([2, 5, 1, 4, 5, 3, 4, 1, 3, 1, 3, 4, 5, 4, 5, 6, 5, 5, 5, 4, 5, 5,
       1, 3, 3, 4, 3, 1, 4, 4, 2, 4, 6, 4, 4, 3, 2, 1, 2, 1, 6, 3, 4, 2,
       3, 1, 6, 2, 5, 6, 4, 5, 6, 6, 6, 3, 2, 6, 1, 5, 2, 1, 3, 6, 1, 4,
       4, 5, 4, 4, 4, 5, 1, 2, 2, 6, 2, 1, 4, 5, 4, 1, 1, 5, 4, 2, 3, 1,
       1, 3, 3, 4, 6, 6, 4, 1, 6, 4, 2, 4])

In [ ]:
np.mean(dice)

3.5

In [ ]:
import random 
for i in range(100):
    dice = np.random.randint(1,6)

dice

# 넘파이 연습문제 7 풀이 하다 실패 

# 8

- 정규분포 주식(All T)

In [49]:
# 5개만 먼저 테스트 
np. random.seed(2021)
rate = np.random.normal(0,0.01,5)
price = 10000
for i in range(5):
    price = np.round(price*(1+rate[i]))
    print(int(price), end=' ')          # round와 int는 가격이라 소수점 필요없어서 

10149 10218 10175 10093 10149 

In [54]:
# 250개 해보기 
np. random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_list=[]
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]         # price_array의 마지막 10개만 추출

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [57]:
# list 아닌 array로 하고싶다면 
# array는 append(늘어나기)가 안되고 공간을 미리 만들어둬야 함 
np. random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_array = np.empty(250,dtype=np.int32)     # 미리 빈 array 만들어 둠

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price 

price_array[-10:]


array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])