In [3]:
import numpy as np

# 1

In [4]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
a = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 2

In [6]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

- 이 행렬에서 값 7을 인덱싱한다

In [7]:
m[1,2]

7

In [8]:
m[1][2]

7

- 이 행렬에서 값 14 을 인덱싱한다.

In [9]:
m[2,4], m[2][4]

(14, 14)

- 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [10]:
m[1,1:3]

array([6, 7])

- 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [11]:
m[1:,2:3]

array([[ 7],
       [12]])

- 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [12]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

# 3

In [13]:
f=m.reshape(-1)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- 이 배열에서 3의 배수를 찾아라.

In [14]:
f%3 ==0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False])

In [15]:
print(np.where(f%3==0))

# 0은 0제외 모든 정수의 배수니까 제외 안 해도 괜찮을까? 
# where을 배운 기억은 없다 

(array([ 0,  3,  6,  9, 12], dtype=int64),)


- 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [16]:
print(np.where(f%4==1))

(array([ 1,  5,  9, 13], dtype=int64),)


- 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [17]:
print(np.where(f%3==0 and f%4==1))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 4

In [ ]:
a=np.eye(5,5,k=-1,dtype=np.int8)
b=np.eye(5,5,k=0,dtype=np.int8)
c=np.eye(5,5,k=1,dtype=np.int8)
3*a + 2*b + c 

# 대박! 풀었다 

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]], dtype=int8)

# 5

In [ ]:
a = np.random.uniform(0,10,(5,6))           # 실수 추출 : uniform
a

array([[0.5903031 , 2.22007595, 4.97792321, 9.1094745 , 3.16669711,
        5.51994293],
       [0.27573375, 3.6380522 , 0.17695254, 6.80429652, 0.24486672,
        6.00128773],
       [3.99194862, 7.27533636, 5.10287833, 5.50345055, 3.68114563,
        7.76868373],
       [8.77509469, 0.45274346, 9.18777908, 1.50218159, 4.16146269,
        7.17272145],
       [5.31113856, 7.50492907, 0.69780529, 2.15038686, 4.45191943,
        5.15116823]])

In [ ]:
# 전체의 최댓값 
a.max()

9.187779081972552

In [ ]:
# 각 행의 합 
a.sum(axis=1)

array([25.5844168 , 17.14118946, 33.32344323, 31.25198297, 25.26734745])

In [ ]:
# 각 행의 최댓값 
a.max(axis=1)

array([9.1094745 , 6.80429652, 7.76868373, 9.18777908, 7.50492907])

In [ ]:
# 각 열의 평균
a.mean(axis=0)

array([3.78884375, 4.21822741, 4.02866769, 5.013958  , 3.14121832,
       6.32276081])

In [ ]:
# 각 열의 최솟값
a.min(axis=0)

array([0.27573375, 0.45274346, 0.17695254, 1.50218159, 0.24486672,
       5.15116823])

# 6

In [18]:
a = np.array([[ 1, 2, 3, 4],[ 46, 99, 100, 71],[ 81, 59, 90, 100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [22]:
# 2 번째 행을 기준으로 각 열을 재정렬하라 
# 전체 오름차순 재정렬-영어 정렬 인덱스 순서 기억한다음 - 다른 데이터들의 인덱스 순서 맞추는 방법으로 풀어보자
a.argsort()


array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]], dtype=int64)

In [19]:
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
a[[0,3,1,2],[0,3,1,2],[0,3,1,2]]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

# 7

In [ ]:
import random 
for i in range(100):
    dice = np.random.randint(1,6)

dice


3

In [ ]:
dice = np.random.randint(1,7,size=100)
dice

array([2, 5, 1, 4, 5, 3, 4, 1, 3, 1, 3, 4, 5, 4, 5, 6, 5, 5, 5, 4, 5, 5,
       1, 3, 3, 4, 3, 1, 4, 4, 2, 4, 6, 4, 4, 3, 2, 1, 2, 1, 6, 3, 4, 2,
       3, 1, 6, 2, 5, 6, 4, 5, 6, 6, 6, 3, 2, 6, 1, 5, 2, 1, 3, 6, 1, 4,
       4, 5, 4, 4, 4, 5, 1, 2, 2, 6, 2, 1, 4, 5, 4, 1, 1, 5, 4, 2, 3, 1,
       1, 3, 3, 4, 6, 6, 4, 1, 6, 4, 2, 4])

In [ ]:
np.mean(dice)

3.5

In [ ]:
import random 
for i in range(100):
    dice = np.random.randint(1,6)

dice

# 넘파이 연습문제 7 풀이 하다 실패 

# 8