# Numpy Part-1

In [1]:
import numpy as np      # 넘파이 사용시 기본 , 항상 설치하고 갑니다. 

### 1. 넘파이 배열 (N-Dimensional Array)

In [2]:
np.array([10,20,30])

array([10, 20, 30])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
np.arange(24).reshape(2,3,4)  # 3차원배열(층,행,열)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

- 위까지는 연습 겸 간단 정리

In [7]:
x= np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [8]:
x.dtype, x.shape, x.ndim, x.size

(dtype('int32'), (5,), 1, 5)

In [9]:
                                    # 배열 만들기
a= np.array([1,3,4,7], float)       # 데이터와 데이터타입 
a

array([1., 3., 4., 7.])

In [10]:
a.dtype, a.shape, a.ndim, a.size        #컴퓨터 기본데이터는 64bit이라서
                                        # shpae는 행렬 모양을 튜플로
                                        # ndim : 차원 
                                        #사이즈 : 배열 요소(element)의 개수

(dtype('float64'), (4,), 1, 4)

In [11]:
# Vector(1차원 데이터 명칭)
a= np.array([1,3,4,7], float)
a

array([1., 3., 4., 7.])

In [12]:
# Matrix(2차원 데이터 명칭)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [13]:
b.dtype, b.shape,b.ndim,b.size

# 데이터 타입은 int(정수형) 정수형 기본은 32bit라서 


(dtype('int32'), (3, 3), 2, 9)

In [14]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
c.dtype, c.shape, c.ndim, c.size


(dtype('int32'), (2, 3, 4), 3, 24)

In [16]:
# dtype 
np.array([1,2,3,4],dtype=np.uint8) # uint/flo..타입과 사이즈정하기


array([1, 2, 3, 4], dtype=uint8)

In [17]:
# reshape
c.size

24

In [18]:
c.reshape(4,6) #사이즈(element 개수)같으면 reshape 가능  

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
c.reshape(3,-1)     # -1: 넘파이에게 결정 (size를 기반으로 row 개수 선정)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [20]:
c.reshape(3,-1,4)       # -1은 한번만 사용 가능 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
a.reshape(4,-1)

array([[1.],
       [3.],
       [4.],
       [7.]])

In [22]:
a.reshape(-1,4)     #array의 shape을 변경(reshape) 숙지해야 함 

array([[1., 3., 4., 7.]])

In [23]:
#del
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [24]:
np.array(b).reshape(9,)

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [25]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [26]:
# b를 변경하여 1차원으로 
# shape은 튜플 
#-1은 size기반 row갯수 결정 
b.reshape(-1)

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [27]:
# T 설명 
# b.reshape(-1) : 1차원으로 변형하는 거 
b.reshape(-1,3) 


array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [28]:
b.reshape(-1,9)

array([[1, 2, 4, 4, 3, 9, 3, 7, 8]])

In [29]:
b.reshape(9,-1)

array([[1],
       [2],
       [4],
       [4],
       [3],
       [9],
       [3],
       [7],
       [8]])

In [30]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
c.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [32]:
b.flatten()     # 다차원 array를  1차원 변환 (다리미 쫙!)

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Slicing

In [33]:
a =np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# 5 꺼내고 싶다면 
a[1][1]

5

In [35]:
a[1,1]      # 리스트 X 넘파이에서 허용하는 형태 

5

In [36]:
a[-1,-2]        # 얘도 가능은 함 #  앞:행 / 뒤:열 

5

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# 4,5를 꺼내고 싶다 
a[1,:2] #[1,0:2]형태, 인덱스 1행의 열-0~2까지인데 앞 0은 생략 


array([4, 5])

In [39]:
#2,3,5,6을 꺼내고 싶다 
a[:,1:]        # 행 : 첫 인덱스~끝 in까지니까 :
                # 열 : .... 0 인덱스 행의 인덱스1~(2,3) + 1 인덱스 행의 인덱스1~(5,6)

array([[2, 3],
       [5, 6]])

In [40]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [41]:
#2,4,3,9
b[:2,1:]

array([[2, 4],
       [3, 9]])

In [42]:
# 4,3,3,_7
b[1:,:2]

array([[4, 3],
       [3, 7]])

In [43]:
#1,4,4,9 # 각 4는 자신의 행에 있는 4가 아님 
b[:2,::2]

array([[1, 4],
       [4, 9]])

### 3. 배열 생성

In [44]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
np.arange(1,4.1,0.5)        

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [47]:
l = np.arange(1,4.1,0.5).tolist()    # 실수 리스트로도 만들 수 있음
l

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [48]:
np.arange(-2,2.01,0.02).size        #2 포함시키려고 저렇게 

201

In [49]:
# linear space
np.linspace(-2,2,201).size      # 위와 아래 두 데이터는 동일 
                                # 201 등분 

                                # 그래프 그릴 때 주로 사용 

201

- ones, zeros, empty

In [50]:
np. ones(shape=(10), dtype = np.int16) 
#내가 만든 사이즈만큼의 데이터를 전부 1로 채워라 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [51]:
np.ones((2,4))      
# 기본이 실수형 
# 행이 2, 열이4, 값이 1로 꽉 채워진 array 생성

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
np.empty(4)         # 기억장소 공간만 만듦. ones/zeros처럼 특정 값으로 초기화X 

array([0., 0., 0., 0.])

- 대각선 : identity, eye 

In [54]:
A * I = A 
사이즈는 정방형 

SyntaxError: invalid syntax (<ipython-input-54-7b8bf19d11c5>, line 2)

In [55]:
# 정방형 (n x n)
np.identity(3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [56]:
# 직사각형 모양(N x M)
np.eye(N=3, M=5, dtype=np.int16)        # 대각선 모양 확인 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [57]:
np.eye(3,5,k=1, dtype=np.int8)

# k는 시작하는 인덱스 값 
# k = -1 이면 첫 행 모두 0, 두번째 행에 첫번째가 -1으로 시작함 (보이지 않는 곳에서 1 입력) 

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

- 데이터 분포에 따른 random sampling 

In [58]:
np.random.seed(2021)        # 랜덤 값 만들어내기 

In [ ]:
np.random.random(4)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])

In [59]:
# 정규분포: normal 
np.random.normal(10,4,4)    # 평균이 10, 표편이 4인 ~을 4개만 꺼냄


array([15.95443621, 12.70404349,  8.32619452,  6.77391675])

In [60]:
# 표준 정규분포
np.random.rand(4)           #np.random.normal(0,1,4)

array([0.99724328, 0.12816238, 0.17899311, 0.75292543])

In [61]:
# 균등(Uniform)분포
np.random.uniform(3,4,4)

array([3.66216051, 3.78431013, 3.0968944 , 3.05857129])