# Numpy - Part 2

In [1]:
import numpy as np

### 4. Operation

In [2]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [3]:
a.sum()

78

In [4]:
a.sum()
# 전체 어레이 대해 정의하면 ()
# 그럼, 가로 세로의 합을 구해보면? 

78

- axis = 0 /  axis = 1
- a[0.0]    a[0,1]
- a[1,0]    a[1,1]
- a[2,0]    a[2,1] 앞 줄이 달라졌다고(?)

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a.sum(axis=0)   #세로 한 줄의 합 x4

array([15, 18, 21, 24])

In [7]:
a.sum(axis=1)   # 가로 한 줄의 합 x3

array([10, 26, 42])

In [8]:
np.sum(a[0])

10

In [9]:
np.sum(a[:2])
#인덱싱/슬라이싱 이랑 같게 생각 

36

- sorting(정렬)

In [10]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [11]:
np.sort(b)      # 행단위 sort 되었으므로 axis = 1
                # axis=1, 오름차순(ascending order) 기본 

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [12]:
b.sort()

In [13]:
b


array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [14]:
np.sort(b, axis=0)  #컬럼단위

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [15]:
c = np.array([42,38,12,25])
np.sort(c)  # 오름차순 sorting 원하면 /내림차순은 reverse였나봄..다 알아


array([12, 25, 38, 42])

In [16]:
# 내림차순일 경우 아래와 같은 방법으로(not reverse)
np.sort(c)[::-1]       # sort 한 다음 

array([42, 38, 25, 12])

In [17]:
np.argsort(c)

#sorting 한 후, 가장 처음 오는 값은 12인데,
# 그때 12의 인덱스는 2310 (?)
# 순서만 알고 싶을 때

array([2, 3, 1, 0], dtype=int64)

In [18]:
c

array([42, 38, 12, 25])

In [19]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [20]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical function

In [21]:
def sigmoid(x):
    return 1./(1+np.exp(-x))

In [22]:
xs = np.array([-10,0,10])

sigmoid(xs)

# sigmoid  잘 알아야..
# 답이 다르게 나와요 

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose (전치)

In [23]:
b 

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [24]:
b.T             # 전치행렬 (2차원 배열이 행과 열 전치)

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstack (배열 결합)


In [25]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
b = np.array([[5,6]]) #shape이 (1x2)
b

array([[5, 6]])

In [27]:
np.vstack((a,b))    # vertical(세로)로 쌓음     # axis =0과 똑같음 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.hstack((a,b.T))      # (horizental)b를 한 번 전치해줘야 가로로 쌓음이 가능
                        # 사이즈 맞으면 T 필요X
                        

array([[1, 2, 5],
       [3, 4, 6]])

In [29]:
a

array([[1, 2],
       [3, 4]])

In [30]:
c=np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
np.hstack((a,c))

array([[1, 2, 0, 1, 2],
       [3, 4, 3, 4, 5]])

In [32]:
np.vstack((a,c.T))

array([[1, 2],
       [3, 4],
       [0, 3],
       [1, 4],
       [2, 5]])

- Array operation
- 기본적인 사칙연산 제공함

In [33]:
a

array([[1, 2],
       [3, 4]])

In [34]:
a + a  

array([[2, 4],
       [6, 8]])

In [35]:
a - a

array([[0, 0],
       [0, 0]])

In [36]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [37]:
a / a 

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [38]:
a + 3

array([[4, 5],
       [6, 7]])

- dot product

In [39]:
a= np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

# dot product는 (2x3)(3x4) 3/3 처럼 중간이 같아야 가능함 
# 그래서 a.b 순서 바꾸면 안됨 

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
np.dot(a,b)     # 그림 그려서 이해 

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [43]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [44]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [45]:
np.dot(b,a), b.dot(a)
# 순서 바꾸면 안됨

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

### 5. Comparison 

- All & Any

In [46]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [48]:
np.any(a>5)     # 하나라도 있는가? (or 연산)

True

In [49]:
np.all(a>5)     # 모두가 5보다 큰가? (and 연산)

False

- Logical operation

In [50]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
b = np.logical_and(a>3 , a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [52]:
np.logical_or(a < 3, a > 7)


array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [53]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.argmax(a), np.argmin(a)        # 제일 마지막/첫번 인덱스 뜸

(9, 0)

In [55]:
# 2차원 argmax, argmin
e = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
e

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 8, 78, 23,  3]])

In [56]:
np.argmax(e, axis=1)
 array([3, 1, 1])      # 각 행마다 가장 큰 요소의 인덱스를 배열로

np.argmax(e, axis=0)
 array([1, 1, 2, 1])   # 각 열마다 가장 큰 요소의 인덱스를 배열로

SyntaxError: invalid character in identifier (<ipython-input-56-81782264cc5e>, line 2)

### 6. Boolean & Fancy index

In [57]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[a>5]  #a에서 elementary 값이 5보다 큰 것만 뽑아라!

array([6, 7, 8, 9])

In [59]:
b       # b의 값은 이런데

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [60]:
a[b]    # a에 넣으면 True 값만 나옴 / 불리언 인덱스! 

array([4, 5, 6])

In [61]:
a[np.logical_or(a<3, a> 7)]

array([0, 1, 2, 8, 9])

In [62]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# fancy index
a[[3,5,7]]      # 인덱스 값이 3,5,7만 가져올래 - 팬시 인덱스!

array([3, 5, 7])

In [64]:
a[[3,5,7,3]]    # 중복해서 가져올 수 있음. 원하는대로 가져옴 

array([3, 5, 7, 3])

### 7. 기술통계

In [65]:
a = np.random.randn(10)     #10개 꺼냄 
a

# 표준 정규 분포 ( N(0,1) 평균 0, 표준편차 1인 분포) 에서 추출한 샘플을 리턴 
# 음수 나올 수 있음(rand와의 차이점)

array([ 3.33556533, -0.51763868,  0.04524353,  0.2440766 ,  2.32276011,
        0.1154553 , -0.13606479, -0.59618747, -0.16261703,  0.42286056])

In [66]:
a.mean() , np.mean(a)   # 평균 구하는 방법 

(0.5073453455234702, 0.5073453455234702)

In [67]:
a.std(), np.std(a)      # 표준편차 구하는 방법 /스탠다드 

(1.2193984663896897, 1.2193984663896897)

In [68]:
a.max(), a.min()        # 최댓값, 최솟값

(3.33556533408787, -0.5961874691421648)

In [69]:
# 4분위수 
np.percentile(a,100), np.percentile(a,0)        # 최댓/최솟값  #맥.민이랑 같음 확인 


(3.33556533408787, -0.5961874691421648)

In [70]:
np.percentile(a,25),np.percentile(a,75)       # 1사분위

(-0.1559789674367652, 0.3781645657650677)

In [71]:
np.percentile(a,50), np.median(a)             # 2사분위

(0.08034941446740777, 0.08034941446740777)

- numpy cheat sheet 