# Numpy - Part 2

In [1]:
import numpy as np

### 4. Operation

In [3]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [4]:
a.sum()
# 전체 어레이 대해 정의하면 ()
# 그럼, 가로 세로의 합을 구해보면? 

78

- axis = 0 /  axis = 1
- a[0.0]    a[0,1]
- a[1,0]    a[1,1]
- a[2,0]    a[2,1] 앞 줄이 달라졌다고(?)

In [5]:
a.sum(axis=0)   #세로 한 줄의 합 x4

array([15, 18, 21, 24])

In [7]:
a.sum(axis=1)   # 가로 한 줄의 합 x3

array([10, 26, 42])

In [8]:
np.sum(a[0])

10

- sorting

In [9]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [10]:
np.sort(b)      # 행단위 sort 되었으므로 axis = 1
                # axis=1, 오름차순(ascending order) 기본 

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [11]:
b.sort()

In [12]:
b


array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [13]:
np.sort(b, axis=0)  #컬럼단위

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [14]:
c = np.array([42,38,12,25])
np.sort(c)  # 오름차순 sorting 원하면 /내림차순은 reverse였나봄..다 알아


array([12, 25, 38, 42])

In [16]:
# 내림차순일 경우 아래와 같은 방법으로(not reverse)
np.sort(c)[::-1]       # sort 한 다음 

array([42, 38, 25, 12])

In [17]:
np.argsort(c)

#sorting 한 후, 가장 처음 오는 값은 12인데,
# 그때 12의 인덱스는 2310 (?)

array([2, 3, 1, 0], dtype=int64)

In [18]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [19]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical function

In [30]:
def sigmoid(x):
    return 1./(1+np.exp(-x))

In [32]:
xs = np.array([-1,0,10])

sigmoid(xs)

# sigmoid  잘 알아야..
# 답이 다르게 나와요 

array([0.26894142, 0.5       , 0.9999546 ])

In [34]:
b 

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [37]:
b.T             # 전치행렬 

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstackz]z


In [38]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [39]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [40]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.hstack((a,b.T))      # np.hstack((a,b)) 에서 변경한 값이 

array([[1, 2, 5],
       [3, 4, 6]])

- Array operation

In [43]:
a + a  

array([[2, 4],
       [6, 8]])

In [44]:
a - a

array([[0, 0],
       [0, 0]])

In [45]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [46]:
a /a 

array([[1., 1.],
       [1., 1.]])

In [47]:
a + 3

array([[4, 5],
       [6, 7]])

In [48]:
a

array([[1, 2],
       [3, 4]])

- dot product

In [52]:
a= np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

# dot product는 (2x3)(3x4) 3/3 처럼 중간이 같아야 가능함 
# 그래서 a.b 순서 바꾸면 안됨 

In [57]:
np.dot(a,b)     # 그림 그려서 이해 

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [54]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [58]:
np.dot(b,a), b.dot(a)
# 순서 바꾸면 안됨

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

### 5. Comparison 

- All & Any

In [60]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [61]:
np.any(a>5)     # 하나라도 있는가? (or 연산)

True

In [64]:
np.all(a>5)     # 모두가 5보다 큰가? (and 연산)

False

- Logical operation

In [65]:
b = np.logical_and(a>3 , a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [66]:
np.logical_or(a < 3, a > 7)


array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [70]:
np.argmax(a), np.argmin(a)        # 제일 마지막/첫번 인덱스 뜸

(9, 0)

### 6. Boolean & Fancy index

In [75]:
a[a>5]  #a에서 elementary 값이 5보다 큰 것만 뽑아라!

array([6, 7, 8, 9])

In [72]:
b       # b의 값은 이런데

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [71]:
a[b]    # a에 넣으면 True 값만 나옴 / 불리언 인덱스! 

array([4, 5, 6])

In [74]:
a[np.logical_or(a<3, a> 7)]

array([0, 1, 2, 8, 9])

In [76]:
# fancy index
a[[3,5,7]]      # 인덱스 값이 3.5,7만 가져올래 - 팬시 인덱스!

array([3, 5, 7])

In [78]:
a[[3,5,7,3]]    # 중복해서 가져올 수 있음. 원하는대로 가져옴 

array([3, 5, 7, 3])

### 7. 기술통계

In [79]:
a = np.random.randn(10)     #10개 꺼냄 
a

array([ 0.22411253, -0.09911385, -0.30746743,  0.51292577,  0.70778277,
        0.60842384, -0.17569454, -0.35263521,  0.96106297,  0.00109936])

In [80]:
a.mean() , np.mean(a)   # 평균 구하는 방법 

(0.20804962090008935, 0.20804962090008935)

In [81]:
a.std(), np.std(a)      # 표준편차 구하는 방법 /스탠다드 

(0.4398672551007652, 0.4398672551007652)

In [82]:
a.max(), a.min()        # 최댓값, 최솟값

(0.9610629725138837, -0.35263520790050534)

In [88]:
# 4분위수 
np.percentile(a,100), np.percentile(a,0)        # 최댓/최솟값  #맥.민이랑 같음 확인 


(0.9610629725138837, -0.35263520790050534)

In [87]:
np.percentile(a,25),np.percentile(a,75)       # 1사분위

(-0.15654937201105018, 0.5845493212752148)

In [86]:
np.percentile(a,50), np.median(a)  

(0.1126059480716814, 0.1126059480716814)

- numpy cheat sheet 